/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Program.java
 *
 * Created on 11.3.2010, 8:04:03
 */

package skolnisoutez;

import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.Random;
import javax.swing.*;
/**
 *
 * @author Felix
 */
public class Program extends javax.swing.JFrame {

    public int PocetMin;
    public int PocetPolicek;
    public int pole[][];
    public String txt;
    public int maxPolicek = 50;
    public int minPolicek = 1;

    /** Creates new form Program */
    public Program() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        policek = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        min = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        PoziceX = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PoziceY = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pocetTahu = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Miny v1.0");

        jLabel1.setText("Policek");

        policek.setText("0");

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Min");

        min.setText("0");

        PoziceX.setEnabled(false);

        jLabel4.setText("Pozice X");

        jLabel5.setText("Pozice Y");

        PoziceY.setEnabled(false);

        jButton2.setText("Tahni");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Pocet tahu");

        pocetTahu.setFont(new java.awt.Font("Tahoma", 1, 24));
        pocetTahu.setText("0");

        jButton3.setText("Cas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMenu1.setText("Soubor");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Nova hra");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Ukoncit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Uroven");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Zacatecnik");
        jMenu3.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Pokrocily");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Expert");
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Info");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem2.setText("Autor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(policek, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(30, 30, 30)
                .addComponent(jButton3)
                .addContainerGap(24, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PoziceX, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PoziceY, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pocetTahu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(466, 466, 466))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(policek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(PoziceX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(PoziceY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(pocetTahu))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-356)/2, (screenSize.height-172)/2, 356, 172);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int tahX,tahY;
        int tahnout = 1;
        
        try{
            tahX = Integer.parseInt(PoziceX.getText());
        }catch (Exception e){
            zobrazVarovani("Spatne zadana pozice X","Varovani");
            tahX = 0;
            tahnout = 0;
        }
        
        try{
            tahY = Integer.parseInt(PoziceY.getText());
        }catch (Exception e){
            tahY = 0;
            tahnout = 0;
            zobrazVarovani("Spatne zadana pozice Y","Varovani");
        }

        if(tahnout==1){
            if(tahX>=this.PocetPolicek || tahY>=this.PocetPolicek){
                zobrazVarovani("Tahate mimo rozsah!","Varovani");
            }else{

                try{
                    int tah = Tahni(tahX,tahY);

                       if(tah==0){
                            ZmenViditelnost(tahX,tahY);
                            VypisSit();
                        ZvysTahy();
                        }else if(tah==2){
                             zobrazHlasku("Tam uz si tahnul! Zkus to znova.","Informace");
                        }else{
                            zobrazHlasku("BOOOOOM!","Informace");
                            ZvysTahy();
                            OdkryjSit();
                            jButton2.setEnabled(false);
                            PoziceX.setEnabled(false);
                            PoziceY.setEnabled(false);
                            String tahy = pocetTahu.getText();
                            zobrazHlasku("Prave jste skoncil.! Ale dekuji vam za hru.\nVas pocet tahu byl: "+tahy,"Konec hry");
                        }

                }catch (Exception e){
                    zobrazChybu("Nepodarilo se tahnout! Vnitrni chyba systemu.","FATAL ERROR");
                }

            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         JOptionPane.showMessageDialog(rootPane, "Tento jednoduchy program vytvoril Milan Felix Sulc.\nStudent na GFMPRK.\nCopyright (c) 2010");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
            policek.setEditable(true);
            min.setEditable(true);
            jButton1.setEnabled(true);
            pocetTahu.setText("0");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  
        boolean pust = true;

        try{
            this.PocetPolicek = Integer.parseInt(policek.getText());
        }catch (Exception e){
            zobrazChybu("Nelze deklarovat pocet policek! Pravdepodobne to neni cislo.","Chyba");
            pust = false;
        }
        try{
            this.PocetMin = Integer.parseInt(min.getText());
        }catch (Exception e){
            zobrazChybu("Nelze deklarovat pocet min! Pravdepodobne to neni cislo.","Chyba");
            pust = false;
        }

        int suma = this.PocetPolicek*this.PocetPolicek;
        if(suma<this.PocetMin){
            pust = false;
            zobrazVarovani("Je vice min nez policek!","Varovani");
        }

        if(this.PocetPolicek>this.maxPolicek || this.PocetPolicek<this.minPolicek){
            pust = false;
            zobrazVarovani("Sit neni z intervalu <10,50>","Varovani");
        }

        if(pust==true){

            policek.setEditable(false);
            min.setEditable(false);
            jButton1.setEnabled(false);
            jButton2.setEnabled(true);
            PoziceX.setEnabled(true);
            PoziceY.setEnabled(true);

            pole = new int[this.PocetPolicek][this.PocetPolicek];

            try{
                GenerujPole();
            }catch (Exception e){
                zobrazChybu("Vyskytla se chyba pri vytvareni pole","Chyba");
            }


            try{
                GenerujMiny();
            }catch (Exception e){
                zobrazChybu("Vyskytla se chyba pri generovani min","Chyba");
            }

            try{
                VypisSit();
            }catch (Exception e){
                zobrazChybu("Vyskytla se chyba pri vypisovani site!","Chyba");
            }

        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    TimerDisplay timer=new TimerDisplay();
    timer.start();
    }//GEN-LAST:event_jButton3ActionPerformed

    public void GenerujPole(){
        for(int x = 0;x<this.PocetPolicek;x++){
            for(int y = 0;y<this.PocetPolicek;y++){
                pole[x][y] = 0;
            }
        }

        //System.out.println("Pole bylo uspesne vytvoreno!");
    }

    public void GenerujMiny(){
        Random nahoda = new Random();


        for(int x = 0;x<this.PocetMin;x++){
            int nxPozice,nyPozice;
            
            nxPozice= nahoda.nextInt(this.PocetPolicek);
            nyPozice= nahoda.nextInt(this.PocetPolicek);

            while(pole[nxPozice][nyPozice] == 1){
                nxPozice = nahoda.nextInt(this.PocetPolicek);
                nyPozice = nahoda.nextInt(this.PocetPolicek);
            }

            pole[nxPozice][nyPozice] = 1;
            System.out.println(Integer.toString(nxPozice)+"-"+Integer.toString(nyPozice));
        } 
        
        //System.out.println("Miny byly uspesne rozmisteny!");
    }

    public int Tahni(int X,int Y){
        if(pole[X][Y]==1){
            return 1;
        }else if(pole[X][Y]==2){
            return 2;
        }else{
            return 0;
        }
    }

    public void VypisSit(){
        for(int z = 0;z<this.PocetPolicek;z++){
            System.out.print("\t"+z);
        }
        System.out.println();
        for(int x = 0;x<this.PocetPolicek;x++){
            System.out.print(x+"");
            for(int y = 0;y<this.PocetPolicek;y++){
                if(pole[x][y]==2){
                    int KamC = PocetKamaradu(x,y);
                    System.out.print("\t"+KamC);
                }else{
                    System.out.print("\t.");
                }

            }
            System.out.println();
        }
        System.out.println("--------------------------------------------------------------");
    }

    public void ZmenViditelnost(int x,int y){
        pole[x][y] = 2;
    }

    public void OdkryjSit(){
        for(int z = 0;z<this.PocetPolicek;z++){
            System.out.print("\t"+z);
        }
        System.out.println();
        for(int x = 0;x<this.PocetPolicek;x++){
            System.out.print(x+"");
            for(int y = 0;y<this.PocetPolicek;y++){
                if(pole[x][y]==1){
                    System.out.print("\t*");
                }else{
                    int KamC = PocetKamaradu(x,y);
                    System.out.print("\t"+KamC);
                }

            }
            System.out.println();
        }
        System.out.println("--------------------------------------------------------------");
    }

    public int PocetKamaradu(int pX,int pY){
        int friends = 0;
        
            // horni rada
            try{
                friends+= (pole[pX-1][pY-1]==1 ? 1:0);
            }catch(Exception e){}

            try{
            friends+= (pole[pX-1][pY]==1 ? 1:0);
            }catch(Exception e){}

            try{
            friends+= (pole[pX-1][pY+1]==1 ? 1:0);
            }catch(Exception e){}

            // stred
            try{
            friends+= (pole[pX][pY-1]==1 ? 1:0);
            }catch(Exception e){}

            try{
            friends+= (pole[pX][pY+1]==1 ? 1:0);
            }catch(Exception e){}

            // horni rada
            try{
            friends+= (pole[pX+1][pY-1]==1 ? 1:0);
            }catch(Exception e){}

            try{
            friends+= (pole[pX+1][pY]==1 ? 1:0);
            }catch(Exception e){}

            try{
            friends+= (pole[pX+1][pY+1]==1 ? 1:0);
            }catch(Exception e){}

            return friends;
    }

    public void ZvysTahy(){
        int zTahu = Integer.parseInt(pocetTahu.getText());
        zTahu++;
        pocetTahu.setText(Integer.toString(zTahu));
    }

    public void zobrazHlasku(String msg,String title){
        JOptionPane.showMessageDialog(rootPane, msg, title, JOptionPane.PLAIN_MESSAGE);
    }
    public void zobrazVarovani(String msg,String title){
        JOptionPane.showMessageDialog(rootPane, msg, title, JOptionPane.WARNING_MESSAGE);
    }
    public void zobrazChybu(String msg,String title){
        JOptionPane.showMessageDialog(rootPane, msg, title, JOptionPane.ERROR_MESSAGE);
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {

        try{
         UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }catch (Exception e){
            e.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Program().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PoziceX;
    private javax.swing.JTextField PoziceY;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField min;
    private javax.swing.JLabel pocetTahu;
    private javax.swing.JTextField policek;
    // End of variables declaration//GEN-END:variables

}
