/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Miny.java
 *
 * Created on 13.3.2010, 22:47:38
 */

package miny;

import java.awt.*;
import java.util.Random;
import javax.swing.*;

/**
 *
 * @author Felix
 */
public class Miny extends javax.swing.JFrame{

    
    public int pocetPolicek = 5;
    public int pocetMin = 10;
    public int velikostPolicek = 25;
    public int pole[][];
    public GridLayout layout;
    public Button tlacitka[][];
    public boolean hra = true;
    public int odkryto = 0;

        /** Creates new form Miny */
    public Miny() {
        initComponents();


        try{
            GenerujPole();
        }catch(Exception e){
            zobrazChybu("Nepovedlo se vygenorovat sit..","Chyba");
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        casLabel = new javax.swing.JLabel();
        cas = new javax.swing.JLabel();
        tahy = new javax.swing.JLabel();
        tahyLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        jSeparator2 = new javax.swing.JSeparator();
        vnejsiPanel = new javax.swing.JPanel();
        hlavniPanel = new javax.swing.JPanel();
        horniMenu = new javax.swing.JMenuBar();
        souborMenu = new javax.swing.JMenu();
        novaHra = new javax.swing.JMenuItem();
        konec = new javax.swing.JMenuItem();
        obtiznostMenu = new javax.swing.JMenu();
        level1 = new javax.swing.JMenuItem();
        level2 = new javax.swing.JMenuItem();
        level3 = new javax.swing.JMenuItem();
        level4 = new javax.swing.JMenuItem();
        level5 = new javax.swing.JMenuItem();
        level6 = new javax.swing.JMenuItem();
        level7 = new javax.swing.JMenuItem();
        level8 = new javax.swing.JMenuItem();
        infoMenu = new javax.swing.JMenu();
        napoveda = new javax.swing.JMenuItem();
        autor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Miny");
        setMinimumSize(new java.awt.Dimension(300, 200));

        casLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        casLabel.setText("Cas:");
        casLabel.setAlignmentY(0.0F);

        cas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cas.setAlignmentY(0.0F);

        tahy.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tahy.setText("0");
        tahy.setAlignmentY(0.0F);

        tahyLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tahyLabel.setText("Tahy:");
        tahyLabel.setAlignmentY(0.0F);

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(casLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(tahyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tahy, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(casLabel)
                            .addComponent(cas, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tahy, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tahyLabel))
                .addContainerGap())
        );

        progressBar.setToolTipText(vratProcentaPB());
        progressBar.setStringPainted(true);

        javax.swing.GroupLayout hlavniPanelLayout = new javax.swing.GroupLayout(hlavniPanel);
        hlavniPanel.setLayout(hlavniPanelLayout);
        hlavniPanelLayout.setHorizontalGroup(
            hlavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        hlavniPanelLayout.setVerticalGroup(
            hlavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout vnejsiPanelLayout = new javax.swing.GroupLayout(vnejsiPanel);
        vnejsiPanel.setLayout(vnejsiPanelLayout);
        vnejsiPanelLayout.setHorizontalGroup(
            vnejsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vnejsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hlavniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );
        vnejsiPanelLayout.setVerticalGroup(
            vnejsiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vnejsiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hlavniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        souborMenu.setText("Soubor");

        novaHra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        novaHra.setText("Nova hra");
        novaHra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaHraActionPerformed(evt);
            }
        });
        souborMenu.add(novaHra);

        konec.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        konec.setText("Konec");
        konec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konecActionPerformed(evt);
            }
        });
        souborMenu.add(konec);

        horniMenu.add(souborMenu);

        obtiznostMenu.setText("Obtiznost");

        level1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, 0));
        level1.setText("4x4");
        level1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level1ActionPerformed(evt);
            }
        });
        obtiznostMenu.add(level1);

        level2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, 0));
        level2.setText("5x5");
        level2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level2ActionPerformed(evt);
            }
        });
        obtiznostMenu.add(level2);

        level3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, 0));
        level3.setText("6x6");
        level3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level3ActionPerformed(evt);
            }
        });
        obtiznostMenu.add(level3);

        level4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, 0));
        level4.setText("7x7");
        level4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level4ActionPerformed(evt);
            }
        });
        obtiznostMenu.add(level4);

        level5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, 0));
        level5.setText("8x8");
        level5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level5ActionPerformed(evt);
            }
        });
        obtiznostMenu.add(level5);

        level6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, 0));
        level6.setText("9x9");
        level6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level6ActionPerformed(evt);
            }
        });
        obtiznostMenu.add(level6);

        level7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, 0));
        level7.setText("10x10");
        level7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level7ActionPerformed(evt);
            }
        });
        obtiznostMenu.add(level7);

        level8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_8, 0));
        level8.setText("15x15");
        level8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                level8ActionPerformed(evt);
            }
        });
        obtiznostMenu.add(level8);

        horniMenu.add(obtiznostMenu);

        infoMenu.setText("Info");

        napoveda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        napoveda.setText("Napoveda");
        napoveda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                napovedaActionPerformed(evt);
            }
        });
        infoMenu.add(napoveda);

        autor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        autor.setText("Autor");
        autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorActionPerformed(evt);
            }
        });
        infoMenu.add(autor);

        horniMenu.add(infoMenu);

        setJMenuBar(horniMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(vnejsiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(vnejsiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setLocation(new java.awt.Point(100, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void konecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konecActionPerformed
        System.exit(0);
    }//GEN-LAST:event_konecActionPerformed

    private void level1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level1ActionPerformed
        this.pocetPolicek = 4;
        GenerujPole();
    }//GEN-LAST:event_level1ActionPerformed

    private void level2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level2ActionPerformed
        this.pocetPolicek = 5;
        GenerujPole();
    }//GEN-LAST:event_level2ActionPerformed

    private void level3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level3ActionPerformed
        this.pocetPolicek = 6;
        GenerujPole();
    }//GEN-LAST:event_level3ActionPerformed

    private void level4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level4ActionPerformed
        this.pocetPolicek = 7;
        GenerujPole();
    }//GEN-LAST:event_level4ActionPerformed

    private void level5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level5ActionPerformed
        this.pocetPolicek = 8;
        GenerujPole();
    }//GEN-LAST:event_level5ActionPerformed

    private void level6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level6ActionPerformed
        this.pocetPolicek = 9;
        GenerujPole();
    }//GEN-LAST:event_level6ActionPerformed

    private void level7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level7ActionPerformed
        this.pocetPolicek = 10;
        GenerujPole();
    }//GEN-LAST:event_level7ActionPerformed

    private void level8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_level8ActionPerformed
        this.pocetPolicek = 15;
        GenerujPole();
    }//GEN-LAST:event_level8ActionPerformed

    private void autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorActionPerformed
         JOptionPane.showMessageDialog(rootPane, "Tento jednoduchy program vytvoril Milan Felix Sulc.\nStudent na GFMPRK.\nCopyright (c) 2010");
    }//GEN-LAST:event_autorActionPerformed

    private void novaHraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaHraActionPerformed
        GenerujPole();
        vynulujPocetTahu();
        vynulujProgressBar();
    }//GEN-LAST:event_novaHraActionPerformed

    private void napovedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_napovedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_napovedaActionPerformed

    public void TlacitkoClick(java.awt.event.ActionEvent evt,int pX,int pY){
        System.out.println(Integer.toString(pX)+Integer.toString(pY));
            
        try{
            int tah = Tahni(pX,pY);

               if(tah==0){
                    ZmenViditelnost(pX,pY);
                    ZvysTahy();
                }else if(tah==2){
                    zobrazHlasku("Tam uz si tahnul! Zkus to znova.","Informace");
                }else{
                    //zobrazHlasku("BOOOOOM!","Informace");
                    ZvysTahy();
                    OdkryjSit();
                    String pocTahu = tahy.getText();
                    zobrazHlasku("Prave jste skoncil.! Ale dekuji vam za hru.\nVas pocet tahu byl: "+pocTahu,"Konec hry");
                }

            ZobrazPrubeh();

        }catch (Exception e){
            zobrazChybu("Nepodarilo se tahnout! Vnitrni chyba systemu.","Chyba");
        }

    }

    public void TlacitkoClick2(java.awt.event.MouseEvent evt,int pX,int pY){

        if(evt.getButton() == 3){
           zobrazHlasku("Tam bude vlajecka","Info");
        }


    }

    private void GenerujPole(){

        hlavniPanel.removeAll();
        layout = new GridLayout ( this.pocetPolicek , this.pocetPolicek) ;
        hlavniPanel.setLayout ( layout ) ;

        pole = new int[this.pocetPolicek][this.pocetPolicek];
        tlacitka = new Button [this.pocetPolicek][this.pocetPolicek];
        for(int x = 0;x<this.pocetPolicek;x++){
            for(int y = 0;y<this.pocetPolicek;y++){
                tlacitka[x][y] = new Button(){
                    public Dimension getPreferredSize() {
                        return getSize();
                    }
                };

                hlavniPanel.add(tlacitka[x][y]);
                final int a = x;
                final int b = y;
                tlacitka[x][y].addMouseListener(new java.awt.event.MouseAdapter() {
                            public void mouseClicked(java.awt.event.MouseEvent evt) {
                                TlacitkoClick2(evt,a,b);
                            }
                });
                 tlacitka[x][y].addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                            TlacitkoClick(evt,a,b);
                    }
                });
                tlacitka[x][y].setSize(this.velikostPolicek,this.velikostPolicek) ;
            }
        }

        vnejsiPanel.setLayout(new FlowLayout(FlowLayout.CENTER));
        hlavniPanel.setSize(this.pocetPolicek*this.velikostPolicek, this.pocetPolicek*this.velikostPolicek);
        this.setSize(this.pocetPolicek*this.velikostPolicek+50, this.pocetPolicek*this.velikostPolicek+140);


        vynulujPocetTahu();
        vynulujProgressBar();

        try{
            GenerujMiny();
        }catch(Exception e){
            zobrazChybu("Nepovedlo se rozmistit miny..","Chyba");
        }


    }


    public void GenerujMiny(){
        Random nahoda = new Random();


        for(int x = 0;x<this.pocetMin;x++){
            int nxPozice,nyPozice;

            nxPozice= nahoda.nextInt(this.pocetPolicek);
            nyPozice= nahoda.nextInt(this.pocetPolicek);

            while(pole[nxPozice][nyPozice] == 1){
                nxPozice = nahoda.nextInt(this.pocetPolicek);
                nyPozice = nahoda.nextInt(this.pocetPolicek);
            }

            pole[nxPozice][nyPozice] = 1;
        }

        //System.out.println("Miny byly uspesne rozmisteny!");
    }


    public int Tahni(int X,int Y){
        if(pole[X][Y]==1){
            return 1;
        }else if(pole[X][Y]==2){
            return 2;
        }else{
            return 0;
        }
    }


    public void ZmenViditelnost(int x,int y){
        if(pole[x][y]!=2){
            this.odkryto++;
        }
        pole[x][y]=2;
        int kamosi = 0;
        kamosi = PocetKamaradu(x,y);
        if(kamosi == 0){
            tlacitka[x][y].setLabel("0");
        }else{
            tlacitka[x][y].setLabel(Integer.toString(kamosi));
            switch(kamosi){
                case 0: tlacitka[x][y].setForeground(new java.awt.Color(255, 255, 255));break;
                case 1: tlacitka[x][y].setForeground(new java.awt.Color(239, 80, 100));break;
                case 2: tlacitka[x][y].setForeground(new java.awt.Color(120, 100, 60));break;
                default: tlacitka[x][y].setForeground(new java.awt.Color(255, 0, 0));
            }
        }
        ZkontrolujOkoli(x,y);
    }

    public void ZkontrolujOkoli(int x, int y){
       
       int a = PocetKamaradu(x,y);
       int Px1,Px2,Px3,Px4;
       if(a == 0){

           try{
             Px1 = StavBunky(x+1,y);
               if(Px1==0){
                   ZmenViditelnost(x+1,y);
               }
           }catch(Exception e){}

           try{
             Px2 = StavBunky(x-1,y);
               if(Px2==0){
                   ZmenViditelnost(x-1,y);
               }
           }catch(Exception e){}

           try{
             Px3 = StavBunky(x,y+1);
               if(Px3==0){
                   ZmenViditelnost(x,y+1);
               }
           }catch(Exception e){}

           try{
             Px4 = StavBunky(x,y-1);
               if(Px4==0){
                   ZmenViditelnost(x,y-1);
               }
           }catch(Exception e){}
      }
    }

    public int StavBunky(int x,int y){
           try{
             if(pole[x][y]==1){
                 return 1;
             }else if(pole[x][y]==2){
                 return 2;
             }else if(pole[x][y]==3){
                 return 3;
             }else{
                 return 0;
             }
           }catch(Exception e){
             return -1;
           }
    }

    public int PocetKamaradu(int pX,int pY){
        int friends = 0;

            // horni rada
            try{
                friends+= (pole[pX-1][pY-1]==1 ? 1:0);
            }catch(Exception e){}

            try{
            friends+= (pole[pX-1][pY]==1 ? 1:0);
            }catch(Exception e){}

            try{
            friends+= (pole[pX-1][pY+1]==1 ? 1:0);
            }catch(Exception e){}

            // stred
            try{
            friends+= (pole[pX][pY-1]==1 ? 1:0);
            }catch(Exception e){}

            try{
            friends+= (pole[pX][pY+1]==1 ? 1:0);
            }catch(Exception e){}

            // horni rada
            try{
            friends+= (pole[pX+1][pY-1]==1 ? 1:0);
            }catch(Exception e){}

            try{
            friends+= (pole[pX+1][pY]==1 ? 1:0);
            }catch(Exception e){}

            try{
            friends+= (pole[pX+1][pY+1]==1 ? 1:0);
            }catch(Exception e){}

            return friends;
    }

    public void ZvysTahy(){
        int zTahu = Integer.parseInt(tahy.getText());
        zTahu++;
        tahy.setText(Integer.toString(zTahu));
    }


    public void OdkryjSit(){
        this.odkryto =  this.pocetPolicek*this.pocetPolicek - this.pocetMin;
        vypisCislo(this.odkryto);
        for(int x = 0;x<this.pocetPolicek;x++){
            for(int y = 0;y<this.pocetPolicek;y++){
                if(pole[x][y]==1){
                    tlacitka[x][y].setLabel("X");
                    tlacitka[x][y].setBackground(new java.awt.Color(255, 0, 0));
                }else{
                    int KamC = PocetKamaradu(x,y);
                    tlacitka[x][y].setLabel(Integer.toString(KamC));
                }

            }
        }
    }

    public void ZobrazPrubeh(){
        float val = (this.odkryto*100)/(this.pocetPolicek*this.pocetPolicek - this.pocetMin);
        vypisCislo((int)val);
        vypisCislo(this.odkryto);
        progressBar.setValue((int)val);
    }


    public void vypisCislo(int cislo){
        System.out.println("Cislo="+Integer.toString(cislo));
    }


    public void zobrazHlasku(String msg,String title){
        JOptionPane.showMessageDialog(rootPane, msg, title, JOptionPane.PLAIN_MESSAGE);
    }
    public void zobrazVarovani(String msg,String title){
        JOptionPane.showMessageDialog(rootPane, msg, title, JOptionPane.WARNING_MESSAGE);
    }
    public void zobrazChybu(String msg,String title){
        JOptionPane.showMessageDialog(rootPane, msg, title, JOptionPane.ERROR_MESSAGE);
    }

    public void vynulujPocetTahu(){
        tahy.setText("0");
    }
    public void vynulujProgressBar(){
        progressBar.setValue(0);
        this.odkryto = 0;
    }

    private String vratProcentaPB(){
        vypisCislo(progressBar.getValue());
        return Integer.toString(progressBar.getValue());
    }
    
    public static void main(String args[]) {

        try
        {
         UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Miny().setVisible(true);
            }
        });
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem autor;
    private javax.swing.JLabel cas;
    private javax.swing.JLabel casLabel;
    public javax.swing.JPanel hlavniPanel;
    private javax.swing.JMenuBar horniMenu;
    private javax.swing.JMenu infoMenu;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenuItem konec;
    private javax.swing.JMenuItem level1;
    private javax.swing.JMenuItem level2;
    private javax.swing.JMenuItem level3;
    private javax.swing.JMenuItem level4;
    private javax.swing.JMenuItem level5;
    private javax.swing.JMenuItem level6;
    private javax.swing.JMenuItem level7;
    private javax.swing.JMenuItem level8;
    private javax.swing.JMenuItem napoveda;
    private javax.swing.JMenuItem novaHra;
    private javax.swing.JMenu obtiznostMenu;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JMenu souborMenu;
    private javax.swing.JLabel tahy;
    private javax.swing.JLabel tahyLabel;
    private javax.swing.JPanel vnejsiPanel;
    // End of variables declaration//GEN-END:variables

}
